### ISSUE TITLE
Full Changelog in GitHub Release too broad

### ISSUE THREAD

**Issue by mhashizume** [puppetlabs/cat-github-actions#82]
## Describe the Bug
When the Module Release workflow generates a new GitHub Release, it includes a "Full Changelog" link that shows every commit between the first commit in the repo and the current release.

This differs from the CHANGELOG.md generated from the Module Release Prep workflow, which also includes a "Full Changelog" link but only shows the commits between the previous and current releases.

## Expected Behavior
I would expect the changelog in a GitHub Release to show a more limited range of changes, or maybe omit the "Full Changelog" link altogether. Many Ruby projects do not include such a link, not all users are interested in just the changes between the two latest releases, and GitHub's UI provides a way to compare the changes between a release and any tag or branch.

## Steps to Reproduce
Click on the "Full Changelog" link in any GitHub Release generated by the Module Release workflow (such as here: https://github.com/puppetlabs/puppetlabs-apt/releases/tag/v9.4.0).

## Environment
n/a

## Additional Context
This was originally reported in the Puppet community Slack: https://puppetcommunity.slack.com/archives/C11LCKKQ9/p1709771123022279

**Comment by LukasAud** [comment]
Hi @mhashizume, this looks like a problem with the changelog generator tool and, unfortunately, we dont own that. We have raised a copy of this issue in the correct GitHub repo: https://github.com/chelnak/gh-changelog/issues/144

We are closing this one off for now. Thanks for reporting.
